# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Host with PostgreSQL
  config.vm.define "pg_ai_ollama" do |pg_ai_ollama|
    pg_ai_ollama.vm.box = "ubuntu/focal64"
    pg_ai_ollama.vm.network "private_network", ip: "192.168.56.29"
    pg_ai_ollama.vm.network "forwarded_port", guest: 5432, host: 6432
    pg_ai_ollama.vm.synced_folder ".", "/vagrant", type: "rsync"
    pg_ai_ollama.vm.provision "shell", path: "provision_pgdb_ai_ubuntu.sh"
  end
  
end

